name: Deploy to Azure

on:
  push:
    branches:
      - deploy  # Trigger the workflow on changes to the "deploy" branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t mysweacrregistry.azurecr.io/library-api:latest .
          echo ${{ secrets.AZ_ACR_PASSWORD }} | docker login mysweacrregistry.azurecr.io -u ${{ secrets.AZ_ACR_USERNAME }} --password-stdin
          docker push mysweacrregistry.azurecr.io/library-api:latest

      # Step 4: Deploy the Docker Image to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp config container set -n my-library-app -g SWE -i mysweacrregistry.azurecr.io/library-api:latest
          az webapp restart -n my-library-app -g SWE
